### PR TITLE
ci: deploy book

### PR DESCRIPTION
**Pull request by fvictorio**

### CODE REVIEW

**Review by agostbiro — APPROVED** [review]
Thanks LGTM. One thought if we want deployments for branches as preview? I'm ok without it, just wanted to bring it up.

**Comment by fvictorio** [comment]
Ah, deploy previews would be nice, but I guess we don't update the book so often for that to be that necessary right now. It would be great to add that in the future though (I don't know how to do that with GitHub pages).

**Comment by Wodann** [comment]
Would this be the URL: https://nomicfoundation.github.io/edr/ ?

**Comment by fvictorio** [comment]
https://nomicfoundation.github.io/edr/book/

**Pull request merged**
