### PR TITLE
chore: update fork url

### PR DESCRIPTION
**Pull request by iosh**
I have limited experience in this area, but I have taken the following steps:
 1. Examined how it is done in the Foundry repository. 
 3. Collected hardcoded URLs in the Solidity file. 
 3. Added names based on the URLs and referenced them in Solidity.
 4. Ran `cargo test`.
 
 The hardcoded URLs in the file `crates/edr_solidity_tests/tests/testdata/default/cheats/RpcUrls.t.sol` `crates/tools/js/benchmark/src/solidity-tests.ts`  have not been modified.
 
 #643

### CODE REVIEW

**Review by agostbiro — CHANGES_REQUESTED** [review]
Thanks for the PR @iosh ! It's a good first step, but the goal is to remove all hard-coded credentials.

For `RpcUrls.t.sol` we could add a new alias with a dummy url and check against that.

For the Rust source files, please replace the hard-coded credentials with getting the Alchemy url from the environment using this function:

https://github.com/NomicFoundation/edr/blob/37008232f781116b4a8fd80d70fa63031284b70f/crates/edr_test_utils/src/env.rs#L20

You can assume that the `ALCHEMY_URL` env var contains a mainnet Alchemy URL. To get the URL for other networks, you can replace `eth-mainnet` with `polygon-mainnet` in the URL for example. It'd be nice if you could create additional helper functions for this in `edr/crates/edr_test_utils/src/env.rs`.

The hard coded credential in `crates/tools/js/benchmark/src/solidity-tests.ts` was added after the issue was created, and it expands the scope significantly, so I'll create a separate issue for this.

Note that you can ignore the CI failure due to missing `ALCHEMY_URL`. It's a permissions issue with Github, but you can test locally by setting the env var and running `cargo test --all-targets --all-features` from the repo root.

Thanks again for the PR and let me know if you have any questions please!

**Review by agostbiro — CHANGES_REQUESTED** [review]
Hey thanks for the changes, we're almost there! I left some comments + please fix the Clippy and formatting errors. You can test these with the following commands from the repo root:

```
cargo clippy --workspace --all-targets --all-features -- --deny warnings
cargo +nightly fmt --all -- --check
```

**Comment by agostbiro** [comment]
Thanks for the changes @iosh! Please also fix the Clippy/formatting issues mentioned here: https://github.com/NomicFoundation/edr/pull/707#pullrequestreview-2394794060

**Comment by iosh** [comment]
Sorry, I forgot to run cargo clippy. I have now re-run cargo clippy, cargo fmt, and cargo test.

**Review by agostbiro — APPROVED** [review]
Thanks, LGTM!

**Comment by iosh** [comment]
Hi @agostbiro can help me find the next issue I can try?

**Pull request merged**
