### PR TITLE
fix: allow missing nonce in remote blocks

### PR DESCRIPTION
**Pull request by Wodann**
Resolved https://github.com/NomicFoundation/edr/issues/536

### CODE REVIEW

**Review by fvictorio — APPROVED** [review]

**Comment by jeremyjams** [comment]
Thank you Wodann! I guess the related release will be in quite a long time since latest release has been out recently?

**Comment by Wodann** [comment]
We usually try to collect a couple of fixes in one release, but there is no cut-off. If need be, we can cut a release sooner :)

cc: @fvictorio

**Comment by fvictorio** [comment]
@jeremyjams done: https://github.com/NomicFoundation/edr/releases/tag/%40nomicfoundation%2Fedr%400.4.2

**Comment by jeremyjams** [comment]
This is very kind, thank you!

**Pull request merged**
