### PR TITLE
ci: add workflows for PR reviews slack notifications

### PR DESCRIPTION
**Pull request by fvictorio**
These workflows will notify us on Slack when a PR review is requested or submitted. They use the jobs defined here: https://github.com/NomicFoundation/github-actions-workflows/tree/main/.github/workflows

### CODE REVIEW

**Review by Wodann — COMMENTED** [review]
Is this necessary, given that we already get GitHub notifications?

**Comment by fvictorio** [comment]
I would personally like it, but maybe we can make it opt-in?

cc @alcuadrado

**Comment by alcuadrado** [comment]
It's opt-out within slack. You just need to mute the conversation with "Github review notifications".

**Comment by alcuadrado** [comment]
> It's opt-out within slack. You just need to mute your conversation with "Github review notifications".

This doesn't work very well. You still get a red circle in the conversation. If you want, I can remove you from the workflow at the org level.

Personally, I haven't felt them as duplication, as these are much more specific than GitHub notifications, more like a call to action, while GH notifications keep me informed about everything.

**Review by Wodann — APPROVED** [review]

**Pull request merged**
